pybind/mgr: fix the TabError error
018-02-08 18:50:10.790 7fcfbb679700 -1 mgr[py] Module not found:
'dashboard'
2018-02-08 18:50:10.790 7fcfbb679700 -1 mgr[py] Traceback (most recent
call last):
  File "/var/ceph/ceph/src/pybind/mgr/dashboard/__init__.py", line 2, in
<module>
    from . module import Module  # NOQA
  File "/var/ceph/ceph/src/pybind/mgr/dashboard/module.py", line 1189
    template = env.get_template("rgw_detail.html")
                                                 ^
TabError: inconsistent use of tabs and spaces in indentation

Fixes: http://tracker.ceph.com/issues/22880
Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 91f83cc0a5e0b7a3ac672bc366a2879fc4a1fd8d)

Conflicts:
src/pybind/mgr/dashboard/module.py

Change-Id: Ia4b1ba78b2dfcd7b7ef122625058e066fb28c598