ceph.in: use a differnt variable for holding thrown exception
otherwise, we will have

$ bin/ceph osd
Traceback (most recent call last):
  File "bin/ceph", line 1178, in <module>
    retval = main()
  File "bin/ceph", line 1109, in main
    verbose)
  File "bin/ceph", line 535, in new_style_command
    valid_dict = validate_command(sigdict, cmdargs, verbose)
  File "/var/ceph/ceph/src/pybind/ceph_argparse.py", line 1083, in
validate_command
    if found or e:
UnboundLocalError: local variable 'e' referenced before assignment

when using python3

Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 487b322b91f9ee13eb9dc5bdc79084e58ed7b38f)