common/time: add time.h for Alpine build
We create the Alpine apk package to view "https://github.com/ceph/ceph/blob/master/README.alpine.md",
at compile time found the following error:
"/src/common/ceph_time.h:209:4: error: invalid use of incomplete type 'struct ceph :: time_detail :: timeval'.

Signed-off-by: huanwen ren <ren.huanwen@zte.com.cn>
(cherry picked from commit 771ecd55f69b0f19833fde82c34ac10cfd567e57)

Conflicts:
src/common/ceph_time.h

Change-Id: I15f57699dd4494b867fd6cc59eecd6cef12092a4