common: Fix Alpine compatability for TEMP_FAILURE_RETRY and ACCESSPERMS
Compiler output:
/ceph/src/common/blkdev.cc: In function 'int64_t get_vdo_stat(int, const char*)':
/ceph/src/common/blkdev.cc:337:3: error: 'TEMP_FAILURE_RETRY' was not declared in this scope
   TEMP_FAILURE_RETRY(::close(fd));

And

/ceph/src/common/common_init.cc: In function 'void common_init_finish(CephContext*)':
/ceph/src/common/common_init.cc:124:21: error: 'ACCESSPERMS' was not declared in this scope
       if (!(ret & (~ACCESSPERMS))) {
                     ^~~~~~~~~~~-

Reported-by: Beierl, Mark <Mark.Beierl@dell.com>
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>
(cherry picked from commit 0314cffbee9c0b3ae6c24aea1bbf56afc2e49a40)

Conflicts:
src/common/blkdev.cc
src/common/common_init.cc

Change-Id: Id4c0c15706cc3c99be1b12597a4fe067b838105a